Repository codefordenver/Comrad, pull requests merged in 2019-07, with the labels that each got.

#518 303 password
  client/src/api/auth/index.js
  client/src/api/auth/passwordChange.js
  client/src/components/Navbar/Navbar.js
  client/src/components/forms/FormPasswordChange/FormPasswordChange.js
  client/src/components/forms/FormPasswordChange/_FormPasswordChange.scss
  client/src/components/forms/FormPasswordChange/index.js
  client/src/pages/ChangePasswordPage/ChangePasswordPage.js
  client/src/pages/ChangePasswordPage/_ChangePasswordPage.scss
  client/src/pages/ChangePasswordPage/index.js
  client/src/redux/auth/actions/index.js
  client/src/redux/auth/actions/passwordChange.js
  client/src/redux/auth/authReducers.js
  client/src/routes/UserRoutes/UserRoutes.js
  client/src/sass/index.scss
  server/v1/controllers/auth/index.js
  server/v1/controllers/auth/passwordChange.js
  server/v1/routes/auth.js
Labels: Still Developing

#520 Alerts in Music Library
  client/src/api/artist/index.js
  client/src/api/artist/update.js
  client/src/components/Alert/Alert.js
  client/src/components/Alert/_Alert.scss
  client/src/components/forms/FormAlbumAdd/FormAlbumAdd.js
  client/src/components/forms/FormAlbumEdit/FormAlbumEdit.js
  client/src/components/forms/FormArtistUpdateName/FormArtistUpdateName.js
  client/src/components/forms/FormTrackAdd/FormTrackAdd.js
  client/src/components/forms/FormTrackEdit/FormTrackEdit.js
  client/src/pages/AlbumAddPage/AlbumAddPage.js
  client/src/pages/AlbumEditPage/AlbumEditPage.js
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/pages/ArtistAddPage/ArtistAddPage.js
  client/src/pages/ArtistViewPage/ArtistViewPage.js
  client/src/pages/LibrarySearchPage/LibrarySearchPage.js
  client/src/pages/TrackAddPage/TrackAddPage.js
  client/src/pages/TrackEditPage/TrackEditPage.js
  client/src/pages/TrackViewPage/TrackViewPage.js
  client/src/redux/album/actions/add.js
  client/src/redux/album/actions/alertClose.js
  client/src/redux/album/actions/edit.js
  client/src/redux/album/actions/findOne.js
  client/src/redux/album/actions/index.js
  client/src/redux/album/actions/remove.js
  client/src/redux/album/albumReducers.js
  client/src/redux/album/albumTypes.js
  client/src/redux/alert/actions/hide.js
  client/src/redux/alert/actions/index.js
  client/src/redux/alert/actions/show.js
  client/src/redux/alert/index.js
  client/src/redux/artist/actions/add.js
  client/src/redux/artist/actions/alertClose.js
  client/src/redux/artist/actions/index.js
  client/src/redux/artist/actions/remove.js
  client/src/redux/artist/actions/update.js
  client/src/redux/artist/artistReducers.js
  client/src/redux/artist/artistTypes.js
  client/src/redux/track/actions/add.js
  client/src/redux/track/actions/alertClose.js
  client/src/redux/track/actions/edit.js
  client/src/redux/track/actions/index.js
  client/src/redux/track/actions/remove.js
  client/src/redux/track/trackReducers.js
  client/src/redux/track/trackTypes.js
  server/v1/controllers/albums/create.js
  server/v1/controllers/albums/createMany.js
  server/v1/controllers/albums/update.js
  server/v1/controllers/albums/utils/index.js
  server/v1/controllers/albums/utils/validateAlbumData.js
  server/v1/controllers/tracks/create.js
  server/v1/controllers/tracks/update.js
Labels: Review

#519 Set up configuration for custom fields. Add Location and Local Artist…
  client/src/api/config/customFieldsForModel.js
  client/src/api/config/index.js
  client/src/api/index.js
  client/src/api/root.js
  client/src/components/CustomFieldsEdit/CustomFieldsEdit.js
  client/src/components/CustomFieldsEdit/index.js
  client/src/components/CustomFieldsView/CustomFieldsView.js
  client/src/components/CustomFieldsView/index.js
  client/src/components/Select/Select.js
  client/src/components/Select/_Select.scss
  client/src/components/forms/FormAlbumEdit/FormAlbumEdit.js
  client/src/pages/AlbumEditPage/AlbumEditPage.js
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/redux/config/actions/customFieldsForModel.js
  client/src/redux/config/actions/index.js
  client/src/redux/config/configReducers.js
  client/src/redux/config/configTypes.js
  client/src/redux/config/index.js
  client/src/redux/index.js
  server/v1/config/base.js
  server/v1/config/dev.js
  server/v1/config/prod.js
  server/v1/config/test.js
  server/v1/controllers/albums/utils/validateAlbumData.js
  server/v1/controllers/config/customFieldsForModel.js
  server/v1/controllers/config/index.js
  server/v1/controllers/index.js
  server/v1/controllers/library/findAll.js
  server/v1/routes/config.js
  server/v1/routes/index.js
Labels: Review

#536 Fix for issue where newly created tracks didn't have artist & album data
  client/src/pages/TrackAddPage/TrackAddPage.js
  server/v1/controllers/tracks/create.js
Labels: Review

#522 476 delete tracks album page
  client/src/components/tables/TableAlbumTracks/TableAlbumTracks.js
  client/src/components/tables/TableAlbumTracks/_TableAlbumTracks.scss
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/sass/base/_reactTable.scss
  client/src/sass/index.scss
Labels: Review

#548 520 edit show 2
  client/src/components/DatePicker/DatePicker__React.js
  client/src/components/Shows/CommonShowForms/RepeatDropdown.js
  client/src/components/Shows/CommonShowForms/ShowDetailsBottom.js
  client/src/components/Shows/CommonShowForms/ShowDetailsTop.js
  client/src/components/Shows/EditShow/Form.js
  client/src/components/Shows/EditShow/Modal.js
  client/src/components/Shows/NewShow/Form.js
  client/src/components/Shows/ViewShow/Form.js
  client/src/components/Shows/_Shows.scss
  client/src/redux/show/showActions.js
  client/src/redux/show/showReducer.js
  package-lock.json
  package.json
  server/v1/controllers/shows/instance/remove.js
  server/v1/controllers/shows/root/update.js
  server/v1/controllers/shows/utils/utils__mongoose.js
Labels: Ready To Merge
