Repository codefordenver/Comrad, pull requests merged in 2019-05, with the labels that each got.

#420 419 Show Calendar - add tooltip calendar
  client/src/components/Modal/_Modal.scss
  client/src/components/Shows/ShowCalendar.js
  client/src/pages/CalendarHomePage/CalendarHomePage.js
  client/src/pages/CalendarHomePage/_CalendarHomePage.scss
Labels: Review

#435 138 host dropdown
  client/src/api/index.js
  client/src/api/root.js
  client/src/api/user/create.js
  client/src/api/user/findOne.js
  client/src/api/user/index.js
  client/src/api/user/search.js
  client/src/api/user/searchHosts.js
  client/src/components/Button/Button.js
  client/src/components/Button/_Button.scss
  client/src/components/Dropdown/_Dropdown.scss
  client/src/components/DropdownHost/DropdownHost.js
  client/src/components/DropdownHost/_DropdownHost.scss
  client/src/components/DropdownHost/index.js
  client/src/components/FormHostAdd/FormHostAdd.js
  client/src/components/FormHostAdd/_formHostAdd.scss
  client/src/components/FormHostAdd/index.js
  client/src/components/FormUserCreate/FormUserCreate.js
  client/src/components/FormUserCreate/_FormUserCreate.scss
  client/src/components/FormUserCreate/index.js
  client/src/components/FormUserSearch/FormUserSearch.js
  client/src/components/Input/Input.js
  client/src/components/Modal/Modal.js
  client/src/components/Modal/_Modal.scss
  client/src/components/NavTest/NavTest.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Shows/NewShow/Form.js
  client/src/components/Shows/ViewShow/DownshiftHost.js
  client/src/components/Shows/ViewShow/Form.js
  client/src/components/TableUsers/TableUsers.js
  client/src/pages/LoginPage/LoginPage.js
  client/src/pages/SignupPage/SignupPage.js
  client/src/pages/UserProfilePage/UserProfilePage.js
  client/src/pages/UserProfilePage/_UserProfilePage.scss
  client/src/pages/UserProfilePage/index.js
  client/src/pages/UserSearchPage/UserSearchPage.js
  client/src/redux/user/userActions.js
  client/src/redux/user/userReducers.js
  client/src/redux/user/userTypes.js
  client/src/routes/UserRoutes/UserRoutes.js
  client/src/sass/base/_typography.scss
  client/src/sass/index.scss
  client/src/utils/api/user/index.js
  client/src/utils/api/user/search.js
  client/src/utils/validation.js
  server/controllers/v1/auth/current.js
  server/controllers/v1/auth/login.js
  server/controllers/v1/shows/create.js
  server/controllers/v1/shows/find.js
  server/controllers/v1/users/create.js
  server/controllers/v1/users/findAll.js
  server/controllers/v1/users/findById.js
  server/controllers/v1/users/index.js
  server/controllers/v1/users/search.js
  server/controllers/v1/users/searchHosts.js
  server/models/v1/user.js
  server/routes/v1/users.js
  server/services/passport.js
Labels: Ready To Merge

#439 _formHostAdd.scss -> _FormHostAdd.scss
  client/src/components/FormHostAdd/_FormHostAdd.scss
Labels: Bug, Ready To Merge, Review

#446 437 album refactor
  client/src/api/album/findOne.js
  client/src/api/album/findOneTracks.js
  client/src/api/album/index.js
  client/src/api/index.js
  client/src/api/root.js
  client/src/components/Root/Root.js
  client/src/components/TableAlbumTracks/TableAlbumTracks.js
  client/src/components/TableUsers/TableUsers.js
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/pages/AlbumViewPage/_AlbumViewPage.scss
  client/src/pages/TrackViewPage/TrackViewPage.js
  client/src/redux/album/actions/findOne.js
  client/src/redux/album/actions/index.js
  client/src/redux/album/albumActions.js
  client/src/redux/album/albumReducers.js
  client/src/redux/album/albumTypes.js
  client/src/redux/album/index.js
  client/src/redux/index.js
  client/src/sass/base/_typography.scss
Labels: Ready To Merge
