Repository codefordenver/Comrad, pull requests merged in 2019-04, with the labels that each got.

#400 User form update
  client/src/components/Filter/Filter.js
  client/src/components/Filter/_Filter.scss
  client/src/components/Filter/index.js
  client/src/components/FormUserSearch/FormUserSearch.js
  client/src/components/FormUserSearch/_FormUserSearch.scss
  client/src/components/TableUsers/TableUsers.js
  client/src/pages/UserSearchPage/UserSearchPage.js
  client/src/utils/api/index.js
  client/src/utils/api/user/index.js
  client/src/utils/api/user/search.js
  server/controllers/userController.js
Labels: Important, Ready To Merge

#379 Add small size button class
  client/src/components/Button/Button.js
  client/src/components/Button/_Button.scss
Labels: Ready To Merge

#375 369 new show/form/validation
  client/src/components/Card/_Card.scss
  client/src/components/DatePicker/DatePicker.js
  client/src/components/DatePicker/_DatePicker.scss
  client/src/components/DatePicker/index.js
  client/src/components/Input/Input.js
  client/src/components/Input/index.js
  client/src/components/Shows/NewShow/Form.js
  client/src/components/Shows/NewShow/Modal.js
  client/src/components/Shows/NewShow/PickerDate.js
  client/src/components/Shows/NewShow/PickerTime.js
  client/src/components/Shows/NewShow/Repeat.js
  client/src/components/Shows/NewShow/RepeatDropdown.js
  client/src/components/Shows/NewShow/Repeat_Dropdown.js
  client/src/components/Shows/_Shows.scss
  client/src/pages/LibrarySearchPage/_LibrarySearchPage.scss
  client/src/pages/UserSearchPage/_UserSearchPage.scss
  client/src/sass/index.scss
Labels: Ready To Merge

#390 Set up albums table for the View Artist page
  client/src/components/TableAlbums/TableAlbums.js
  client/src/pages/ArtistViewPage/ArtistViewPage.js
  client/src/pages/ArtistViewPage/_ArtistViewPage.scss
  client/src/redux/artist/artistActions.js
  client/src/redux/artist/artistReducers.js
  client/src/redux/artist/artistTypes.js
  server/controllers/artistController.js
  server/routes/api/artist.js
Labels: Ready To Merge

#391 389 add artist
  client/src/components/FormArtistAdd/FormArtistAdd.js
  client/src/components/FormArtistAdd/_formArtistAdd.scss
  client/src/components/FormArtistAdd/index.js
  client/src/pages/ArtistAddPage/ArtistAddPage.js
  client/src/pages/ArtistAddPage/_ArtistAddPage.scss
  client/src/pages/ArtistAddPage/index.js
  client/src/pages/LibrarySearchPage/LibrarySearchPage.js
  client/src/redux/artist/artistActions.js
  client/src/redux/artist/artistReducers.js
  client/src/redux/artist/artistTypes.js
  client/src/routes/LibraryRoutes/LibraryRoutes.js
  client/src/sass/index.scss
Labels: Ready To Merge

#407 update(ArtistViewPage): Added LargeText component and did some tweaki…
  client/src/components/Alert/Alert.md
  client/src/components/Alert/_Alert.scss
  client/src/components/Filter/Filter.md
  client/src/components/FilterUsers/FilterUsers.js
  client/src/components/FilterUsers/_FilterUsers.scss
  client/src/components/FilterUsers/index.js
  client/src/pages/ArtistViewPage/ArtistViewPage.js
Labels: Feature

#408 Update to User Search and Alert Component
  client/src/components/Alert/Alert.js
  client/src/components/Alert/_Alert.scss
  client/src/components/FormUserSearch/FormUserSearch.js
  client/src/components/FormUserSearch/_FormUserSearch.scss
  client/src/components/TableUsers/TableUsers.js
  client/src/pages/UserSearchPage/UserSearchPage.js
  client/src/redux/user/userActions.js
  client/src/redux/user/userReducers.js
  client/src/redux/user/userTypes.js
  client/src/utils/api/index.js
  client/src/utils/api/user/index.js
  client/src/utils/api/user/search.js
  server/controllers/userController.js
Labels: Ready To Merge

#410 Artist View Page Update
  client/src/components/ButtonIcon/ButtonIcon.js
  client/src/components/ButtonIcon/_ButtonIcon.scss
  client/src/components/FormArtistUpdateName/FormArtistUpdateName.js
  client/src/components/Input/Input.js
  client/src/components/Input/_Input.scss
  client/src/components/LargeText/LargeText.js
  client/src/components/TableAlbums/TableAlbums.js
  client/src/components/TableAlbums/index.js
  client/src/components/TableArtistAlbums/TableArtistAlbums.js
  client/src/components/TableArtistAlbums/_TableArtistAlbums.scss
  client/src/components/TableArtistAlbums/index.js
  client/src/pages/ArtistViewPage/ArtistViewPage.js
  client/src/pages/ArtistViewPage/_ArtistViewPage.scss
  client/src/redux/artist/artistActions.js
  client/src/redux/artist/artistReducers.js
  client/src/redux/artist/artistTypes.js
Labels: Ready To Merge

#412 Merge branch 287-list-albums-for-artist again
  client/src/components/FormArtistAdd/FormArtistAdd.js
  client/src/components/FormArtistAdd/_formArtistAdd.scss
  client/src/components/FormArtistAdd/index.js
  client/src/pages/ArtistAddPage/ArtistAddPage.js
  client/src/pages/ArtistAddPage/_ArtistAddPage.scss
  client/src/pages/ArtistAddPage/index.js
  client/src/pages/LibrarySearchPage/LibrarySearchPage.js
  client/src/redux/artist/artistActions.js
  client/src/redux/artist/artistReducers.js
  client/src/redux/artist/artistTypes.js
  client/src/routes/LibraryRoutes/LibraryRoutes.js
  client/src/sass/index.scss
Labels: Ready To Merge

#415 251 react modal update
  client/package-lock.json
  client/package.json
  client/src/components/Modal/Modal.js
  client/src/components/Modal/_Modal.scss
  client/src/components/Shows/EditShow/Modal.js
  client/src/components/Shows/NewShow/Modal.js
  client/src/components/Shows/ViewShow/DownshiftHost.js
  client/src/components/Shows/ViewShow/Modal.js
  client/src/components/Shows/_Shows.scss
Labels: Ready To Merge

#395 291 list tracks for album
  client/src/components/TableAlbumTracks/TableAlbumTracks.js
  client/src/components/TableAlbumTracks/_TableAlbumTracks.scss
  client/src/components/TableAlbumTracks/index.js
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/redux/album/albumActions.js
  client/src/redux/album/albumReducers.js
  client/src/redux/album/albumTypes.js
  client/src/redux/album/index.js
  client/src/redux/index.js
  server/controllers/albumController.js
  server/models/track.js
  server/routes/api/album.js
Labels: Review

#411 317 dropdown component
  client/src/components/Dropdown/Dropdown.js
  client/src/components/Dropdown/Dropdown.md
  client/src/components/Dropdown/DropdownCircle.js
  client/src/components/Dropdown/DropdownIcon.js
  client/src/components/Dropdown/DropdownItem.js
  client/src/components/Dropdown/DropdownPlus.js
  client/src/components/Dropdown/_Dropdown.scss
  client/src/components/Dropdown/index.js
  client/src/components/Navbar/Navbar.js
  client/src/components/Shows/ViewShow/DownshiftHost.js
  client/src/pages/LibrarySearchPage/LibrarySearchPage.js
  server/controllers/v1/users/randomUser.js
Labels: Ready To Merge

#421 Skip preflight check instructions
  docs/getting_started.md
Labels: Ready To Merge

#427 427 - Update of dates calculation for individual shows without repeat
  server/controllers/v1/shows/create.js
  server/controllers/v1/shows/find.js
  server/controllers/v1/shows/findAll.js
  server/controllers/v1/shows/findByDate.js
  server/controllers/v1/shows/index.js
  server/controllers/v1/shows/utils/utils.js
  server/routes/v1/shows.js
Labels: Review

#429 422- Host Dropdown Update
  client/src/components/Shows/ViewShow/DownshiftHost.js
  client/src/redux/show/showActions.js
  server/controllers/v1/shows/update.js
  server/routes/v1/shows.js
Labels: Review
