Repository codefordenver/Comrad, pull requests merged in 2019-08, with the labels that each got.

#543 502 genre
  client/src/api/genre/findAll.js
  client/src/api/genre/index.js
  client/src/api/index.js
  client/src/api/root.js
  client/src/components/Select/Select.js
  client/src/components/forms/FormAlbumAdd/FormAlbumAdd.js
  client/src/components/forms/FormAlbumEdit/FormAlbumEdit.js
  client/src/pages/AlbumViewPage/AlbumViewPage.js
  client/src/redux/genre/actions/findAll.js
  client/src/redux/genre/actions/index.js
  client/src/redux/genre/genreReducers.js
  client/src/redux/genre/genreTypes.js
  client/src/redux/genre/index.js
  client/src/redux/index.js
  package.json
  server/v1/controllers/albums/findById.js
  server/v1/controllers/genres/findAll.js
  server/v1/controllers/genres/index.js
  server/v1/controllers/index.js
  server/v1/routes/genres.js
  server/v1/routes/index.js
Labels: Review

#525 500 addbutton
  client/src/components/Shows/NewShow/Form.js
  client/src/pages/CalendarHomePage/CalendarHomePage.js
  client/src/pages/CalendarHomePage/_CalendarHomePage.scss
  client/src/redux/show/showActions.js
  client/src/redux/show/showReducer.js
  client/src/redux/show/showTypes.js
Labels: Ready To Merge, Review

#567 import withRouter, wrap connect function with withRouter
  client/src/components/Navbar/Navbar.js
Labels: Ready To Merge, Review

#572 Devin/components/card
  client/src/components/CardV2/CardBodyV2.js
  client/src/components/CardV2/CardV2.js
  client/src/components/CardV2/_CardV2.scss
  client/src/components/CardV2/index.js
  client/src/components/Form/Form.js
Labels: Ready To Merge

#566 Changed access control around searchHosts endpoint. Integrated host d…
  cli/seedAccessControl/grants/Hosts.js
  cli/seedAccessControl/grants/index.js
  client/src/components/Shows/ShowCalendar.js
  client/src/components/Shows/ViewShow/Form.js
  client/src/pages/ShowBuilderPage/ShowBuilderPage.js
  client/src/redux/show/showActions.js
  client/src/utils/shows.js
  server/v1/models/accessControl.js
  server/v1/routes/users.js
Labels: Review

#568 523 toobig
  client/src/components/Modal/_Modal.scss
  client/src/components/Shows/_Shows.scss
Labels: Ready To Merge, Review
